FROM python:3.11-slim

WORKDIR /app

# Instala dependencias de sistema necesarias para compilar paquetes
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    libffi-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

# Usa el comando flask con recarga automática, para desarrollo
CMD ["python", "script.py"]